options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Installing zip..."
        apt-get update && apt-get install -y zip
        echo "Creating deployment ZIP archive..."
        zip -r deployment-artifact.zip . -x ".git/*" ".gitignore"

  # Step 2: Upload the ZIP to GCS
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "deployment-artifact.zip", "gs://${_GCS_BUCKET}/artifacts/"]

  # Step 3: Copy cleanup and rsync scripts to VM
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "scp"
      - "cicd-scripts/cleanup.sh"
      - "cicd-scripts/rsync.sh"
      - "${_VM_INSTANCE}:~/"
      - "--zone=${_ZONE}"

  # Step 4: Download ZIP from GCS to VM & install unzip in a single SSH session
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - |
        set -e
        sudo apt-get update && sudo apt-get install -y unzip
        gsutil cp gs://${_GCS_BUCKET}/artifacts/deployment-artifact.zip ~/artifact.zip

  # Step 5: Run cleanup script before deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "bash ~/cleanup.sh"

  # Step 6: Extract ZIP and sync files using rsync
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        gcloud compute ssh "${_VM_INSTANCE}" --zone="${_ZONE}" --command "
          sudo chown -R \$(whoami):\$(whoami) /var/www/html &&
          sudo chmod -R 775 /var/www/html &&
          sudo unzip -o ~/artifact.zip -d /var/www/html &&
          bash ~/rsync.sh
        "


  # Step 7: Restart Apache after deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "sudo systemctl restart apache2"

# Upload artifacts to GCS (only the ZIP file)
artifacts:
  objects:
    location: "gs://${_GCS_BUCKET}/artifacts/"
    paths:
      - "deployment-artifact.zip"

substitutions:
  _VM_INSTANCE: "simplify-001"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "simplify-storage-bucket"
  _BRANCH_NAME: "main"
