options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Installing zip..."
        apt-get update && apt-get install -y zip
        echo "Creating deployment ZIP archive..."
        zip -r deployment-artifact.zip . -x .git/*

  # Step 2: Upload the ZIP file to GCS
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "cp"
      - "deployment-artifact.zip"
      - "gs://${_GCS_BUCKET}/artifacts/deployment-artifact.zip"

  # Step 3: Ensure the ZIP file exists before copying to the VM
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Checking if ZIP exists in GCS..."
        gsutil ls gs://${_GCS_BUCKET}/artifacts/deployment-artifact.zip || exit 1
        echo "Copying ZIP to VM..."
        gcloud compute ssh ${_VM_INSTANCE} --zone=${_ZONE} --command "gsutil cp gs://${_GCS_BUCKET}/artifacts/deployment-artifact.zip ~/artifact.zip"

  # Step 4: Run cleanup before deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "bash -c 'bash cicd-scripts/cleanup.sh'"

  # Step 5: Extract ZIP and sync files using rsync
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "bash -c 'unzip -o ~/artifact.zip -d /var/www/html && bash cicd-scripts/rsync.sh'"

  # Step 6: Restart Apache after deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "sudo systemctl restart apache2"

# Upload ZIP file as an artifact to GCS
artifacts:
  objects:
    location: "gs://${_GCS_BUCKET}/artifacts/"
    paths:
      - "deployment-artifact.zip"

substitutions:
  _VM_INSTANCE: "simplify-001"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "simplify-storage-bucket"
  _BRANCH_NAME: "main"
