options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Sync files from the Cloud Build workspace to the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - scp
      - '--recurse'
      - '/workspace/*'
      - '${_VM_INSTANCE}:~/my-php-app'
      - '--zone=${_ZONE}'

  # Deploy code and restart Apache service on the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - '${_VM_INSTANCE}'
      - '--zone=${_ZONE}'
      - '--command="sudo cp -r ~/my-php-app/* /var/www/html && sudo systemctl restart apache2"'
substitutions:
  _VM_INSTANCE: "webapp-instance-20250210-150325"
  _ZONE: "us-central1-c"
