timeout: 900s  # Moved timeout to the top level

steps:
  - name: "gcr.io/cloud-builders/bash"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Extracting branch name..."
        BRANCH_NAME="${_BRANCH_NAME}"
        BRANCH_NAME="${BRANCH_NAME:-$SHORT_SHA}" # Fallback to commit hash if branch name is empty
        sed -i "s|\$BRANCH_NAME_REPLACE|${BRANCH_NAME}|g" cicd-scripts/rsync.sh
        sed -i "s|\$BRANCH_NAME_REPLACE|${BRANCH_NAME}|g" cicd-scripts/cleanup.sh"

  - name: "gcr.io/cloud-builders/bash"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Installing zip and creating archive..."
        apt-get update && apt-get install -y zip
        zip -r deployment-artifact.zip . -x .git/*

  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "cp"
      - "deployment-artifact.zip"
      - "gs://${_GCS_BUCKET}/${_BRANCH_NAME}/deployment-artifact.zip"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_INSTANCE_NAME}"
      - "--command"
      - "bash -s < cicd-scripts/cleanup.sh"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_INSTANCE_NAME}"
      - "--command"
      - "bash -s < cicd-scripts/rsync.sh"

options:
  logging: CLOUD_LOGGING_ONLY  # Keep logging under options
