steps:
  # Sync app files directly to VM
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/your-org/my-php-app.git /workspace/app

  # Sync and deploy directly to the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - '${_VM_INSTANCE}'
      - '--zone=${_ZONE}'
      - '--command="sudo rm -rf /var/www/html/* && sudo cp -r /workspace/app/* /var/www/html && sudo systemctl restart apache2"'
substitutions:
  _VM_INSTANCE: "webapp-instance-20250210-150325"
  _ZONE: "us-central1-c"
