options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Creating deployment ZIP archive..."
        zip -r deployment-artifact.zip . -x ".git/*" ".gitignore"

  # Step 2: Upload the ZIP to GCS
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "deployment-artifact.zip", "gs://${_GCS_BUCKET}/artifacts/"]

  # Step 3: Copy deployment ZIP to the VM
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "scp"
      - "deployment-artifact.zip"
      - "${_VM_INSTANCE}:~/"
      - "--zone=${_ZONE}"

  # Step 4: Cleanup, Extract, and Rsync to /var/www/pradeeptest-${_BRANCH_NAME}/
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - |
        set -e
        echo "Installing required dependencies..."
        sudo apt-get update && sudo apt-get install -y unzip rsync

        DEPLOY_DIR="/var/www/pradeeptest-${_BRANCH_NAME}"
        TMP_DIR="/tmp/pradeeptest-${_BRANCH_NAME}"

        echo "Cleaning up previous deployment..."
        [ -d "$TMP_DIR" ] && sudo rm -rf "$TMP_DIR"
        [ -d "$DEPLOY_DIR" ] && sudo rm -rf "$DEPLOY_DIR"

        echo "Extracting deployment ZIP..."
        sudo mkdir -p "$TMP_DIR"
        sudo unzip -o ~/deployment-artifact.zip -d "$TMP_DIR"

        echo "Syncing files to $DEPLOY_DIR..."
        sudo mkdir -p "$DEPLOY_DIR"
        sudo rsync -av --delete "$TMP_DIR/" "$DEPLOY_DIR/"

        echo "Setting correct ownership and permissions..."
        sudo chown -R www-data:www-data "$DEPLOY_DIR"
        sudo chmod -R 775 "$DEPLOY_DIR"

        if [ -d "$DEPLOY_DIR/data/" ]; then
          echo "Setting ownership for data directory..."
          sudo chown -R www-data:www-data "$DEPLOY_DIR/data/"
        fi

  # Step 5: Restart Apache after deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "sudo systemctl restart apache2"

substitutions:
  _VM_INSTANCE: "simplify-001"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "simplify-storage-bucket"
  _BRANCH_NAME: "main"
