options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Installing zip..."
        apt-get update && apt-get install -y zip
        echo "Creating deployment ZIP archive..."
        zip -r deployment-artifact.zip . -x ".git/*" ".gitignore"

  # Step 2: Upload the ZIP to GCS
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "deployment-artifact.zip", "gs://${_GCS_BUCKET}/artifacts/"]

  # Step 3: Copy deployment ZIP to the VM
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "scp"
      - "deployment-artifact.zip"
      - "${_VM_INSTANCE}:~/"
      - "--zone=${_ZONE}"

  # Step 4: Extract, Sync, and Set Permissions
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - |
        set -e
        echo "Installing required dependencies..."
        sudo apt-get update && sudo apt-get install -y unzip rsync

        TMP_DIR="/tmp/pradeeptest-${_BRANCH_NAME}"
        FINAL_DEST="/var/www/pradeeptest-${_BRANCH_NAME}"

        echo "Cleaning up previous deployment..."
        sudo rm -rf "$TMP_DIR"
        sudo mkdir -p "$TMP_DIR"

        echo "Extracting deployment ZIP..."
        sudo unzip -o ~/deployment-artifact.zip -d "$TMP_DIR"

        echo "Syncing files to $FINAL_DEST..."
        sudo mkdir -p "$FINAL_DEST"
        sudo rsync -av --delete "$TMP_DIR/" "$FINAL_DEST/"

        echo "Setting correct ownership and permissions..."
        sudo chown -R ubuntu:ubuntu "$FINAL_DEST"
        sudo chmod -R 775 "$FINAL_DEST"

        if [ -d "$FINAL_DEST/data/" ]; then
          echo "Setting www-data ownership for $FINAL_DEST/data/"
          sudo chown -R www-data:www-data "$FINAL_DEST/data/"
        fi

  # Step 5: Restart Apache after deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "sudo systemctl restart apache2"

substitutions:
  _VM_INSTANCE: "simplify-001"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "simplify-storage-bucket"
  _BRANCH_NAME: "main"
