options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: "ubuntu"
    id: "Create Deployment ZIP"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Installing zip..."
        apt-get update && apt-get install -y zip
        echo "Creating deployment ZIP archive..."
        zip -r deployment-artifact.zip . -x ".git/*" ".gitignore"

  # Step 2: Upload the ZIP file to GCS
  - name: "gcr.io/cloud-builders/gsutil"
    id: "Upload ZIP to GCS"
    args: ["cp", "deployment-artifact.zip", "gs://${_GCS_BUCKET}/artifacts/"]

  # Step 3: Copy the ZIP file from GCS to the target VM
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Copy ZIP to VM"
    args:
      - "compute"
      - "scp"
      - "deployment-artifact.zip"
      - "${_VM_INSTANCE}:~/"
      - "--zone=${_ZONE}"

  # Step 4: Prepare Deployment Directory on VM
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Prepare Deployment on VM"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - |
        set -e
        echo "Installing dependencies..."
        sudo apt-get update && sudo apt-get install -y unzip rsync

        TMP_DIR="/tmp/pradeeptest-${_BRANCH_NAME}"
        DEPLOY_DIR="/var/www/pradeeptest-${_BRANCH_NAME}"

        echo "Cleaning up old deployment..."
        sudo rm -rf "$DEPLOY_DIR" || { echo "Cleanup failed"; exit 1; }
        sudo rm -rf "$TMP_DIR" || { echo "Cleanup failed"; exit 1; }

  # Step 5: Extract and Sync Deployment Files
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Extract and Sync Deployment"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - |
        set -e
        TMP_DIR="/tmp/pradeeptest-${_BRANCH_NAME}"
        DEPLOY_DIR="/var/www/pradeeptest-${_BRANCH_NAME}"

        echo "Extracting new deployment..."
        mkdir -p "$TMP_DIR" || { echo "mkdir failed"; exit 1; }
        unzip -o ~/deployment-artifact.zip -d "$TMP_DIR" || { echo "Unzip failed"; exit 1; }

        echo "Syncing files to deployment directory..."
        sudo mkdir -p "$DEPLOY_DIR" || { echo "mkdir failed"; exit 1; }
        sudo rsync -av --delete "$TMP_DIR/" "$DEPLOY_DIR/" || { echo "rsync failed"; exit 1; }

  # Step 6: Set Correct Permissions
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Set Permissions"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - |
        set -e
        DEPLOY_DIR="/var/www/pradeeptest-${_BRANCH_NAME}"

        echo "Setting ownership and permissions..."
        sudo chown -R www-data:www-data "$DEPLOY_DIR" || { echo "chown failed"; exit 1; }
        sudo find "$DEPLOY_DIR" -type d -exec chmod 755 {} + || { echo "chmod failed"; exit 1; }
        sudo find "$DEPLOY_DIR" -type f -exec chmod 644 {} + || { echo "chmod failed"; exit 1; }

  # Step 7: Restart Apache
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Restart Apache"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "sudo systemctl restart apache2"

substitutions:
  _VM_INSTANCE: "simplify-001"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "simplify-storage-bucket"
  _BRANCH_NAME: "main"
