options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Installing zip..."
        apt-get update && apt-get install -y zip
        echo "Creating deployment ZIP archive..."
        zip -r deployment-artifact.zip . -x ".git/*" ".gitignore"

  # Step 2: Upload the ZIP to GCS
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "deployment-artifact.zip", "gs://${_GCS_BUCKET}/artifacts/"]

  # Step 3: Copy deployment ZIP to the VM
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "scp"
      - "deployment-artifact.zip"
      - "${_VM_INSTANCE}:~/"
      - "--zone=${_ZONE}"

  # Step 4: Cleanup old deployment, Extract, and Rsync to /var/www/html
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - |
        set -e
        echo "Installing dependencies..."
        sudo apt-get update && sudo apt-get install -y unzip rsync
        
        echo "Cleaning up old deployment..."
        sudo rm -rf /tmp/pradeeptest-${_BRANCH_NAME}
        
        echo "Extracting new deployment..."
        mkdir -p /tmp/pradeeptest-${_BRANCH_NAME}
        unzip -o ~/deployment-artifact.zip -d /tmp/pradeeptest-${_BRANCH_NAME}

        echo "Syncing files to /var/www/html..."
        sudo rsync -av --delete /tmp/pradeeptest-${_BRANCH_NAME}/ /var/www/html/

        echo "Setting correct ownership and permissions..."
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 775 /var/www/html

  # Step 5: Restart Apache after deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "sudo systemctl restart apache2"

substitutions:
  _VM_INSTANCE: "simplify-001"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "simplify-storage-bucket"
  _BRANCH_NAME: "main"
