options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Creating deployment ZIP archive..."
        zip -r deployment-artifact.zip . -x .git/*

  # Step 2: Upload ZIP file as an artifact to GCS
artifacts:
  objects:
    location: 'gs://${_GCS_BUCKET}/artifacts/'
    paths:
      - 'deployment-artifact.zip'

  # Step 3: Copy ZIP file from GCS to the VM instance
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "cp"
      - "gs://${_GCS_BUCKET}/artifacts/deployment-artifact.zip"
      - "./artifact.zip"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "scp"
      - "artifact.zip"
      - "${_VM_INSTANCE}:~/artifact.zip"
      - "--zone=${_ZONE}"

  # Step 4: Run the cleanup script on the VM
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "bash -s < cicd-scripts/cleanup.sh"

  # Step 5: Run rsync script on the VM to deploy files
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "bash -s < cicd-scripts/rsync.sh"

  # Step 6: Restart Apache after deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "sudo systemctl restart apache2"

substitutions:
  _VM_INSTANCE: "webapp-instance-20250210-150325"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "test-pradeep-123ssx"
