options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: "gcr.io/cloud-builders/bash"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Creating deployment ZIP archive..."
        zip -r artifact.zip . -x ".git/*"

  # Step 2: Upload the ZIP file to GCS bucket
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "cp"
      - "artifact.zip"
      - "gs://${_GCS_BUCKET}/${_BRANCH_NAME}/artifact.zip"

  # Step 3: Copy the ZIP file from GCS to the VM instance
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "scp"
      - "artifact.zip"
      - "${_VM_INSTANCE}:~/artifact.zip"
      - "--zone=${_ZONE}"

  # Step 4: Run the cleanup script on the VM
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "bash -s < cicd-scripts/cleanup.sh"

  # Step 5: Run rsync script on the VM to deploy files
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "bash -s < cicd-scripts/rsync.sh"

  # Step 6: Restart Apache after deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--command"
      - "sudo systemctl restart apache2"

substitutions:
  _VM_INSTANCE: "simplify-001"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "simplify-storage-bucket"
  _BRANCH_NAME: "main"
