options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create a ZIP file of the deployment contents (excluding .git)
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Installing zip..."
        apt-get update && apt-get install -y zip
        echo "Creating deployment ZIP archive..."
        zip -r deployment-artifact.zip . -x ".git/*" ".gitignore"

  # Step 2: Upload the ZIP to GCS
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "deployment-artifact.zip", "gs://${_GCS_BUCKET}/artifacts/"]

  # Step 3: Copy deployment ZIP to the VM
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "scp"
      - "deployment-artifact.zip"
      - "${_VM_INSTANCE}:~/"
      - "--zone=${_ZONE}"
      - "--tunnel-through-iap"

  # Step 4: Cleanup old deployment, Extract, and Rsync to /var/www/pradeeptest-${BRANCH_NAME}/
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--tunnel-through-iap"
      - "--command"
      - |
        set -e
        echo "Installing dependencies..."
        sudo apt-get update && sudo apt-get install -y unzip rsync

        echo "Cleaning up old deployment..."
        sudo rm -rf /var/www/pradeeptest-${BRANCH_NAME} || { echo "Cleanup failed"; exit 1; }
        sudo rm -rf /tmp/pradeeptest-${BRANCH_NAME} || { echo "Cleanup failed"; exit 1; }

        echo "Extracting new deployment..."
        mkdir -p /tmp/pradeeptest-${BRANCH_NAME} || { echo "mkdir failed"; exit 1; }
        unzip -o ~/deployment-artifact.zip -d /tmp/pradeeptest-${BRANCH_NAME} || { echo "Unzip failed"; exit 1; }

        echo "Syncing files to /var/www/pradeeptest-${BRANCH_NAME}/..."
        sudo mkdir -p /var/www/pradeeptest-${BRANCH_NAME} || { echo "mkdir failed"; exit 1; }
        sudo rsync -av --delete /tmp/pradeeptest-${BRANCH_NAME}/ /var/www/pradeeptest-${BRANCH_NAME}/ || { echo "rsync failed"; exit 1; }

        echo "Setting correct ownership and permissions..."
        sudo chown -R www-data:www-data /var/www/pradeeptest-${BRANCH_NAME} || { echo "chown failed"; exit 1; }
        sudo find /var/www/pradeeptest-${BRANCH_NAME} -type d -exec chmod 755 {} + || { echo "chmod failed"; exit 1; }
        sudo find /var/www/pradeeptest-${BRANCH_NAME} -type f -exec chmod 644 {} + || { echo "chmod failed"; exit 1; }

  # Step 5: Restart Apache after deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "${_VM_INSTANCE}"
      - "--zone=${_ZONE}"
      - "--tunnel-through-iap"
      - "--command"
      - "sudo systemctl restart apache2"

substitutions:
  _VM_INSTANCE: "simplify-001"
  _ZONE: "us-central1-c"
  _GCS_BUCKET: "simplify-storage-bucket"
